Added new trimmer makefiles

diff --git a/examples/trimmer/gzip/Makefile b/examples/trimmer/gzip/Makefile
--- a/examples/trimmer/gzip/Makefile
+++ b/examples/trimmer/gzip/Makefile
@@ -7,15 +7,11 @@ GZIP_PATCH=gzip.patch
 
 GZIP_MANIFEST=${GZIP}.manifest
 
-HELPER_SCRIPT=./build.sh
-HELPER_TAR=helper_scripts_and_files.tar.gz
-
-
-OUT_DIR?=slash
+OUT_DIR?=trimmer
 LOG_FILE?=logs
 
-BITCODE_WRAPPER?=gclang
-BITCODE_EXTRACT?=get-bc
+BITCODE_WRAPPER?=wllvm
+BITCODE_EXTRACT?=extract-bc
 
 all: ${GZIP_BITCODE}
 
@@ -31,20 +27,18 @@ test_compress:
 	@echo "\t\tTest Compress"
 	@echo "File Existence Check:"
 	@# Testing if compressed file produced
-	@cp helper_huffman.c huffman.c
-	@cp huffman.c ${OUT_DIR}/ && \
-	cd ${OUT_DIR}/ && \
+	@cp huffman.c ${OUT_DIR}/work_dir && \
+	cd ${OUT_DIR}/work_dir && \
 	./gzip_fin_stripped && \
-	test -f /OCCAM-Benchmarks/examples/trimmer/gzip/huffman.c.gz && echo "\tgzip test compress file exist? Passed!" || echo "gzip test compress file exist? Failed!" 
+	test -f huffman.c.gz && echo "\tgzip test compress file exist? Passed!" || echo "gzip test compress file exist? Failed!" 
 	@echo "Comparing File Sizes:"
 	@# Printing File sizes
-	@cp helper_huffman.c huffman.c
 	@echo -n "\tSource File Size:\t"
 	@stat -L -c %s huffman.c
 	@echo -n "\tCompressed File Size:\t"
-	@stat -L -c %s /OCCAM-Benchmarks/examples/trimmer/gzip/huffman.c.gz
+	@stat -L -c %s ${OUT_DIR}/work_dir/huffman.c.gz
 	@echo "Output comparison to Baseline:"
-	@cmp -i 10 ./huffman_unspecialized.c.gz /OCCAM-Benchmarks/examples/trimmer/gzip/huffman.c.gz; \
+	@cmp -i 10 ./huffman.c.gz ${OUT_DIR}/work_dir/huffman.c.gz; \
 	RETVAL=$$?; \
 	if [ $$RETVAL -eq 0 ]; then \
 		echo "\tgzip test baseline compare? Passed!"; \
@@ -56,8 +50,7 @@ test_compress:
 
 	
 .PHONY: ${GZIP_BITCODE}
-${GZIP_BITCODE}: ${GZIP_NAME} 
-	cp helper_huffman.c huffman.c && \
+${GZIP_BITCODE}: ${GZIP_NAME}
 	cp ${GZIP_PATCH} ${GZIP_NAME} && \
 	cd ${GZIP_NAME} && \
 	patch -p0 -f -R -i ./${GZIP_PATCH} && \
@@ -65,20 +58,15 @@ ${GZIP_BITCODE}: ${GZIP_NAME}
 	CC=${BITCODE_WRAPPER} make && \
 	${BITCODE_EXTRACT} ${GZIP} && \
 	mv ${GZIP_BITCODE} ../  && \
-	${GZIP} --keep --force --quiet ../huffman.c
-	mv huffman.c.gz huffman_unspecialized.c.gz	
+	${GZIP} --keep --force --quiet ../huffman.c 
 		
 ${OUT_DIR}:
 	mkdir -p ${OUT_DIR}
 
 ${GZIP_NAME}:
-	wget https://gnu.askapache.com/gzip/gzip-1.3.12.tar.gz
 	tar -xvzf ./${GZIP_TAR}
 
-${HELPER_SCRIPT}:
-	tar -xvf ./${HELPER_TAR}
-
 clean:
-	rm -rf ${GZIP_NAME} ${GZIP_TAR}
-	rm -rf *manifest *.bc *slash* huffman.c huffman_unspecialized.c.gz
-	rm -rf ${OUT_DIR}
+	rm -rf ${GZIP_NAME}
+	rm *.bc
+	rm -r ${OUT_DIR}
